### ISSUE TITLE
Pseudo elements announced

### ISSUE THREAD

**Issue by vavroom** [nicolas-steenhout/main#86]
◦	Pseudo-elements are announced for Jaws/Chrome and VO/Safari. The decorative quote mark for each testimonial and the em dash on each side of the testimonial author’s name

**Comment by vavroom** [comment]
@digilou Just tested this - the quote and the emdash around the names are announced. I think that makes for a weird experience.

**Comment by digilou** [comment]
@vavroom That is VERY interesting. Pseudo elements didn't work that way before, which meant adding real content there was a problem. Agreed on the weird experience!

Thoughts:
* I may need to resort to a background image rather than this `::before` hack, if you like the faded quote mark.
* Emdashes are purely decorative... should we just eliminate them altogether and lean on other visual design (different font size, color, etc)?

**Comment by vavroom** [comment]
@digilou Yes, let's drop the emdash, and go for a background damage for the quote. Only thing to be aware of is what does the background image look like in windows high contrast mode?

**Comment by digilou** [comment]
@vavroom If it's a purely decorative background image, I wouldn't say it's essential to appear in WHCM. There would be space there, but nothing that should look odd.
